export class ButtonVerber {
  commands = [
    'adjust title',
    'again',
    'another plz',
    'another',
    'boop the button',
    'button',
    'calm your titles',
    'cat /dev/random',
    'change career',
    'change job',
    'change title',
    'create title',
    'create',
    'derive new title',
    'enhance title',
    'enhance your calm',
    'enhance',
    'enterprise me',
    'fire ze missiles',
    'fizz buzz it',
    'generate new title',
    'generate title',
    'give it to a script kiddie',
    'initiate job hunt',
    'irritate HR',
    'jquery that shit in',
    'make it so',
    'moar',
    'more',
    'needs more jpeg',
    'new title',
    'new',
    'one more',
    'play it again',
    'produce new title',
    'punch it',
    'random.choose(titles)',
    'realign parameters',
    'recalculate title',
    'recreate title',
    'regenerate title',
    'reprocess title',
    'reprocess',
    'reset parameters',
    'reset title',
    'reset',
    'respawn title',
    'respawn',
    'reticulate splines',
    'retrieve new title',
    'retrieve title',
    'ship it',
    'shuffle the deck',
    'simulate demotion',
    'simulate promotion',
    'simulate transfer',
    'something else',
    'spawn title',
    'start over',
    'stimulate promotion',
    'surprise your manager',
    'synthesize title',
    'tease recruiters',
    'that\'s not good enough',
    'this time with emphasis',
    'title',
    'titleGenerator.getRandom()',
    'try again',
    'yet another',
    '{{buttonTitle}}',
  ]

  getRandom = function() {
    return this.commands[Math.floor(Math.random() * this.commands.length)];
  }
}
